path: F:/PythonCode/WatchCondition/data
train: images/training_2
val: images/validation_2


# Classes
names:
  0: heavy_scratch
  1: light_scratch
  2: dent
  3: watch_face


# Hyperparameters

# Augmentation
hsv_h: 0.015 # (float) image HSV-Hue augmentation (fraction)
hsv_s: 0.3 # (float) image HSV-Saturation augmentation (fraction)
hsv_v: 0.3 # (float) image HSV-Value augmentation (fraction)
degrees: 180.0 # (float) image rotation (+/- deg)
translate: 0.1 # (float) image translation (+/- fraction)
scale: 0.3 # (float) image scale (+/- gain)
shear: 0 # (float) image shear (+/- deg)
perspective: 0.0 # (float) image perspective (+/- fraction), range 0-0.001
flipud: 0.3 # (float) image flip up-down (probability)
fliplr: 0.5 # (float) image flip left-right (probability)
bgr: 0.1 # (float) image channel BGR (probability)
mosaic: 0.7 # (float) image mosaic (probability)
mixup: 0.1 # (float) image mixup (probability)
copy_paste: 0.1 # (float) segment copy-paste (probability)
auto_augment: randaugment # (str) auto augmentation policy for classification (randaugment, autoaugment, augmix)
erasing: 0.4 # (float) probability of random erasing during classification training (0-0.9), 0 means no erasing, must be less than 1.0.
crop_fraction: 0.8 # (float) image crop fraction for classification (0.1-1), 1.0 means no crop, must be greater than 0.